DROP DATABASE IF EXISTS ECOMMERCE;
CREATE DATABASE ECOMMERCE;
USE ECOMMERCE;

CREATE TABLE clients
(
    id INT AUTO_INCREMENT PRIMARY KEY
    client_name VARCHAR(20) NOT NULL
    email VARCHAR(30) NOT NULL UNIQUE
    reg_date DATE NOT NULL
)

CREATE TABLE products
(
    
)