DROP DATABASE IF EXISTS STUDIO_VETERINARIO;
CREATE DATABASE STUDIO_VETERINARIO;
USE STUDIO_VETERINARIO;

CREATE TABLE PET_
(
    PET_ID INT AUTO_INCREMENT PRIMARY KEY,
    PET_NAME VARCHAR(25),
    PET_RACE VARCHAR(15),
    PET_SPECIES VARCHAR(15),
    PET_AGE INT
);

CREATE TABLE OWNER_
(
    OWNER_ID INT AUTO_INCREMENT PRIMARY KEY,
    PET_ID INT,
    FOREIGN KEY (PET_ID) REFERENCES PET_(PET_ID),
    OWNER_NAME VARCHAR(30),
    OWNER_LASTNAME VARCHAR(30),
    OWNER_PHONE_NUMBER VARCHAR(12),
    OWNER_EMAIL VARCHAR(40),
    OWNER_EXTERNAL_TOKEN VARCHAR(50),
    OWNER_PASSWORD VARCHAR(12),
    OWNER_FC VARCHAR(16)
);

CREATE TABLE VISIT_
(
    VISIT_ID INT AUTO_INCREMENT PRIMARY KEY,
    PET_ID INT,
    FOREIGN KEY (PET_ID) REFERENCES PET_(PET_ID),
    VISIT_DATE DATE,
    VISIT_DIAGNOSIS VARCHAR(32),
    VISIT_PROBLEM VARCHAR(32)
);

CREATE TABLE VET_
(
    VET_ID INT AUTO_INCREMENT PRIMARY KEY,
    VET_NAME VARCHAR(30),
    VET_LASTNAME VARCHAR(30),
    VET_EXTERNAL_TOKEN VARCHAR(50),
    VET_EMAIL VARCHAR(40),
    VET_SPEC VARCHAR(32),
    VISIT_ID INT,
    FOREIGN KEY (VISIT_ID) REFERENCES VISIT_(VISIT_ID)
);

SHOW TABLES;