DROP DATABASE IF EXISTS SUPERMARKETS;
CREATE DATABASE SUPERMARKETS;
USE SUPERMARKETS;
CREATE TABLE MERCH_(
    _MERCH_ID INT AUTO_INCREMENT PRIMARY KEY,
    _NAME VARCHAR(30)
);
CREATE TABLE SUPERMARKET_(
    _MARKET_ID INT AUTO_INCREMENT PRIMARY KEY,
    _NAME VARCHAR(15),
    _CITY_NAME VARCHAR(15)
);
CREATE TABLE SALE_(
    _SALE_ID INT AUTO_INCREMENT PRIMARY KEY,
    _SALE_DATE DATE,
    _QUANTITY INT,
    _PRICE DECIMAL(3, 2),
    _MERCH_ID INT,
    _MARKET_ID INT,
    FOREIGN KEY (_MERCH_ID) REFERENCES MERCH_(_MERCH_ID),
    FOREIGN KEY (_MARKET_ID) REFERENCES SUPERMARKET_(_MARKET_ID)
);
-- TO PRINT ALL THE TABLES IN A DATABASE, FIRST USE THE DB YOU WANT THEN RUN SHOW TABLES;
SHOW DATABASES;
SHOW TABLES;
INSERT INTO MERCH_
VALUES (NULL, "KKKoniglio");
INSERT INTO SUPERMARKET_
VALUES (NULL, "Vanoni", "Rho"),
    (NULL, "Essepunga", "Viterbo"),
    (NULL, "SonoArmato", "Lecco"),
    (NULL, "Esselunga", "Rho");
INSERT INTO SALE_
VALUES (NULL, "1989-06-04", 5, 7.23, 1, 1);
-- QUERIES 1
SELECT *
FROM MERCH_;
-- QUEES 1
SELECT *
FROM SUPERMARKET_;
-- QUERS 1
SELECT *
FROM SALE_;
-- QUERY 2
SELECT _NAME
FROM SUPERMARKET_
WHERE _CITY_NAME = "Rho";

-- NOTA PER PROF, w SE LEGGE QUESTO COMMENTO, MI LASCI EVENTUALI CORREZIONI NEL COMMENTO PRIVATO DEL COMPITO, POI SE MI RICORDO MAGARIFI FINISCO E NON DEVO FINIRE SISTEMI E RETI